---
rec5EjFj3Q0uDa0Ud: User is receiving duplicates for each alert message, ranging from
  2-5 additional messages on top of the original (and correct) alert to both email
  and text
recaIJbkAetcVXPcl: "(hahaha)(hahaha)(hahaha) 學長專用語言， 並不是垃圾語言 他僅是LINE的表情符號而已 (hahaha)(hahaha)(hahaha)
  學長專用語言， 並不是垃圾語言 他僅是LINE的表情符號而已"
recvffgi8B7EncOpg: User has 5 faces saved for PorchCam's facial recognition, but the
  system isn't letting him save more than those 5. He's tried removing existing ones
  and adding different ones, etc.
