keywords:
  - "武漢肺炎"
  - "新冠肺炎"
  - "新型冠狀病毒"
  - "2019冠狀病毒病"
  - "coronavirus"
  - "covid-19"
0: |-
  想要知道關於 COVID-19 的一些知識與最新消息嗎？現在你可以輸入號碼來問美玉姨喔，美玉姨提供目前來自 WHO 的指引，與各項最新統計資訊。
  1. 最新統計，包含全球，台灣，與疫情最嚴重的十個國家。
  2. 我怎麼自我保護？
  3. 破除常見迷思
  4. 旅行建議

  請輸入數字開啟對話，或輸入 ok 結束對話。
1: "Coronavirus::Data.new.process"
2: |-
  關於保護自己：

  🧼 常洗手
  👄 避免觸碰你的眼睛與口鼻
  💪當你咳嗽或打噴嚏的時候，用衛生紙或手肘蓋住嘴巴
  🚷 不要去擁擠的地方
  🏠 如果你覺得不舒服的話請待在家，即便只有一點點發燒或咳嗽
  🤒 如果你有發燒咳嗽或是呼吸困難，馬上尋找醫療資源，像是先打電話詢問。

  輸入其他數字或是 0 回到選單。
3: |-
  關於迷思：

  🔅 乾洗手殺掉新型冠狀病毒的效率並不高
  🔅 紫外線燈不能用來消毒手或是其他的身體部位
  🔅 量體溫不能辨認出無症狀感染者
  🔅 酒精不能殺掉已經進入身體內的病毒（但體外可以）
  🔅 目前沒有疫苗可以預防新型冠狀病毒，既存的肺炎疫苗也不可以
  🔅 常常用鹽水洗手或是漱口並不能保護你不被感染，也不能治癒
  🔅 吃大蒜並不能保護你不被感染，也不能治癒
  🔅 新型冠狀病毒並不是只感染老年人
  🔅 抗生素並不能對抗病毒，只能對抗細菌
  🔅 目前並沒有任何特效藥可以對抗新型冠狀病毒

  輸入其他數字或是 0 回到選單。
4: |-
  關於旅行建議：

  可以的話，千 萬 不 要 旅 行！
  若必須旅行請注意多洗手，別去人多的地方，遮住口鼻。

  輸入其他數字或是 0 回到選單。
